//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int Id_Review { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<int> Game_Id { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Comment { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual User User { get; set; }
    }
}
